# Generated by Django 3.1.4 on 2020-12-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20201221_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
