# Generated by Django 3.1.4 on 2020-12-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_auto_20201228_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(default='2012-09-04 06:00:00'),
        ),
    ]
