# Generated by Django 3.1.4 on 2021-01-20 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_location', models.CharField(choices=[('HD', 'Hall D'), ('ELT', 'Edozian lecture THeatre'), ('Coleng', 'College of Engineering')], max_length=10)),
                ('mobile_number', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note')),
            ],
        ),
    ]
