# Generated by Django 3.1.4 on 2020-12-28 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20201221_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_pic',
        ),
        migrations.AddField(
            model_name='note',
            name='deadline',
            field=models.DateTimeField(default='2012-09-04 06:00:00'),
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note')),
            ],
        ),
    ]
